# Generated by Django 4.0.2 on 2022-03-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
